/**
 * Export data to different file formats.
 * Both `path` and `fs/promises` are imported lazily so this module is
 * importable in edge / browser runtimes without a filesystem shim.
 * Calling any toXxx() / exportAll() function in a non-Node environment will
 * throw at runtime, which is expected — file export requires a filesystem.
 */
let _path = null;
async function joinPath(...parts) {
  if (!_path) _path = await import('path');
  return _path.join(...parts);
}

let fsPromises = null;
async function fs() {
  if (!fsPromises) fsPromises = await import('fs/promises');
  return fsPromises;
}

/**
 * Export data as JSON file
 * @param {{ data: any, path: string, pretty?: boolean }} opts
 */
export async function toJSON({ data, path, pretty = true }) {
  const { writeFile } = await fs();
  const content = pretty ? JSON.stringify(data, null, 2) : JSON.stringify(data);
  await writeFile(path, content, 'utf8');
  return { format: 'json', path, size: Buffer.byteLength(content) };
}

/**
 * Export data as CSV
 * Works on arrays of objects.
 * @param {{ data: any[], path: string, columns?: string[] }} opts
 */
export async function toCSV({ data, path, columns }) {
  const { writeFile } = await fs();
  const rows = Array.isArray(data) ? data : [data];
  const cols = columns || Object.keys(rows[0] || {});

  const escape = (v) => {
    if (v === null || v === undefined) return '';
    const s = String(v);
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"`
      : s;
  };

  const lines = [
    cols.join(','),
    ...rows.map((row) => cols.map((c) => escape(row[c])).join(',')),
  ];

  const content = lines.join('\n');
  await writeFile(path, content, 'utf8');
  return { format: 'csv', path, rows: rows.length, columns: cols };
}

/**
 * Export data as Markdown table
 * @param {{ data: any[], path: string, title?: string }} opts
 */
export async function toMarkdown({ data, path, title }) {
  const { writeFile } = await fs();
  const rows = Array.isArray(data) ? data : [data];
  const cols = Object.keys(rows[0] || {});

  const lines = [];
  if (title) lines.push(`# ${title}\n`);

  lines.push(`| ${cols.join(' | ')} |`);
  lines.push(`| ${cols.map(() => '---').join(' | ')} |`);
  rows.forEach((row) => {
    const vals = cols.map((c) => {
      const v = row[c];
      if (typeof v === 'object' && v !== null) return JSON.stringify(v).slice(0, 50);
      return String(v ?? '');
    });
    lines.push(`| ${vals.join(' | ')} |`);
  });

  const content = lines.join('\n');
  await writeFile(path, content, 'utf8');
  return { format: 'markdown', path, rows: rows.length };
}

/**
 * Export data as HTML table
 * @param {{ data: any[], path: string, title?: string }} opts
 */
export async function toHTML({ data, path, title = 'Bemora Export' }) {
  const { writeFile } = await fs();
  const rows = Array.isArray(data) ? data : [data];
  const cols = Object.keys(rows[0] || {});

  const thRow = cols.map((c) => `<th>${c}</th>`).join('');
  const bodyRows = rows.map((row) => {
    const tds = cols.map((c) => {
      const v = row[c];
      const val = typeof v === 'object' && v !== null ? JSON.stringify(v) : String(v ?? '');
      return `<td>${val}</td>`;
    }).join('');
    return `<tr>${tds}</tr>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
  body { font-family: system-ui, sans-serif; padding: 2rem; background: #0f172a; color: #e2e8f0; }
  h1 { color: #818cf8; margin-bottom: 1.5rem; }
  table { width: 100%; border-collapse: collapse; background: #1e293b; border-radius: 8px; overflow: hidden; }
  th { background: #6366f1; color: white; padding: 12px 16px; text-align: left; }
  td { padding: 10px 16px; border-bottom: 1px solid #334155; }
  tr:last-child td { border: none; }
  tr:hover td { background: #273349; }
  .meta { color: #64748b; font-size: 0.85rem; margin-top: 1rem; }
</style>
</head>
<body>
<h1>${title}</h1>
<table>
<thead><tr>${thRow}</tr></thead>
<tbody>${bodyRows}</tbody>
</table>
<p class="meta">Generated by bemora · ${new Date().toISOString()} · ${rows.length} rows</p>
</body>
</html>`;

  await writeFile(path, html, 'utf8');
  return { format: 'html', path, rows: rows.length };
}

/**
 * Export data in multiple formats at once
 * @param {{ data: any, dir: string, name: string, formats: string[] }} opts
 */
export async function exportAll({ data, dir = '.', name = 'bemora-export', formats = ['json', 'csv', 'html'] }) {
  const { mkdir } = await fs();
  await mkdir(dir, { recursive: true });
  const results = [];

  for (const format of formats) {
    const path = await joinPath(dir, `${name}.${format}`);
    try {
      if (format === 'json')     results.push(await toJSON({ data, path }));
      if (format === 'csv')      results.push(await toCSV({ data: Array.isArray(data) ? data : [data], path }));
      if (format === 'html')     results.push(await toHTML({ data: Array.isArray(data) ? data : [data], path, title: name }));
      if (format === 'md')       results.push(await toMarkdown({ data: Array.isArray(data) ? data : [data], path, title: name }));
    } catch (err) {
      results.push({ format, path, error: err.message });
    }
  }

  return { exported: results, dir, name };
}
